apiVersion: v1
data:
  Dockerfile: |-
    FROM python:3.8-slim

    WORKDIR /app

    COPY ./requirements.txt /app/requirements.txt

    RUN apt-get update \
        && apt-get install gcc -y \
        && apt-get clean

    RUN pip install -r /app/requirements.txt \
        && rm -rf /root/.cache/pip

    COPY . /app/
  requirements.txt: |-
    asyncpg==0.20.1
    databases[postgresql]==0.2.6
    fastapi==0.48.0
    SQLAlchemy==1.3.13
    uvicorn==0.11.2
    httpx==0.11.1
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: movie-service
  name: movie-service-cm0
