apiVersion: v2
name: exam-jenkins
description: A Helm chart for deploying Jenkins on Kubernetes.

type: application

version: 0.1.0

appVersion: "1.16.0"

maintainers:
  - name: Samuel
    email: shmoulik.an@gmail.com

keywords:
  - jenkins
